rm -rf ./build
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/gcc4.9.4/opencv2 -DWITH_OPENEXR=OFF -DWITH_OPENMP=OFF -DWITH_OPENCL=OFF -DBUILD_EXAMPLES=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_WITH_DEBUG_INFO=ON -DBUILD_opencv_apps=OFF
cmake --build build --target install -- -j 7
